In [1]:
import pandas as pd
from numpy import datetime64
import numpy as np

#from folium.features import DivIcon

pd.set_option('display.max_rows', None)

df_backup = pd.read_csv("/Users/ytsang/Desktop/FYP/1.Data/eta_prediction.csv")
df = df_backup

df.columns = ["Loc", "Vehicle", "ShipNo", "Start-Lng", "Start-Lat", "Dest-Lng", "Dest-Lat", 
    "Time-1", "Time-2", "Time-3", "Time-4", "Time-5"]

for i in range(5):
    column = "Time-"+ str(i+1)
    df[column] = pd.to_datetime(df[column], errors = 'coerce', format='%Y-%m-%d %H:%M:%S')

convert_dict = {"Loc": str, "Vehicle": str, "ShipNo": str, "Start-Lng": str, "Start-Lat": str, "Dest-Lng": str, "Dest-Lat": str,
    "Time-5": datetime64, "Time-5": datetime64, "Time-5": datetime64, "Time-5": datetime64, "Time-5": datetime64}
df = df.astype(convert_dict)

df["planDurn"] = df["Time-2"].dropna()-df["Time-1"].dropna()
df["actDurn"] = df["Time-4"].dropna()-df["Time-3"].dropna()
#df["planTaskTime"] = df["Time-5"].dropna()-df["Time-1"].dropna()
#df["actTaskTime"] = df["Time-5"].dropna()-df["Time-3"].dropna()
#df["plannedRemainTime"] = df["Time-5"].dropna().astype(datetime64)-df["Time-2"].dropna().astype(datetime64)
#df["actualRemainTime"] = df["Time-5"].dropna().astype(datetime64)-df["Time-4"].dropna().astype(datetime64)

df['companyCode'] = df['ShipNo'].str[:3]
df['sysCode'] = df['ShipNo'].str[:7].str[4:]
df['countryCode'] = df['ShipNo'].str[:11].str[8:]
df['warehouse'] = df['ShipNo'].str[:16].str[12:]
df['shipNo'] = df['ShipNo'].str[-9:]



df = df.rename({"Time-1": "planStartTime", "Time-2": "planEndTime", "Time-3": "actStartTime", 
    "Time-4": "actEndTime", "Time-5": "MiscTime"}, axis = "columns")

df["origLoc"] = df[["Start-Lng", "Start-Lat"]].agg(', '.join, axis=1)
df["destLoc"] = df[["Dest-Lng", "Dest-Lat"]].agg(', '.join, axis=1)
df = df.drop(["Start-Lng", "Start-Lat", "Dest-Lng", "Dest-Lat", 'ShipNo'], axis=1)

cols = ["Loc", "Vehicle", "warehouse", "shipNo", "origLoc", "destLoc", "planStartTime", "planEndTime", "actStartTime", "actEndTime", 
    "MiscTime", "planDurn", "actDurn", "countryCode", "sysCode", "companyCode"]

df = df[cols]

df.head(15)

/var/folders/rx/s42f27kn5j5ddqzlhz7qr2yw0000gn/T/ipykernel_2516/2500322238.py:9: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_backup = pd.read_csv("/Users/ytsang/Desktop/FYP/1.Data/eta_prediction.csv")
/var/folders/rx/s42f27kn5j5ddqzlhz7qr2yw0000gn/T/ipykernel_2516/2500322238.py:21: FutureWarning: Passing unit-less datetime64 dtype to .astype is deprecated and will raise in a future version. Pass 'datetime64[ns]' instead
  df = df.astype(convert_dict)

,Loc,Vehicle,warehouse,shipNo,origLoc,destLoc,planStartTime,planEndTime,actStartTime,actEndTime,MiscTime,planDurn,actDurn,countryCode,sysCode,companyCode
0,CHN,NO-LIMIT,TSX0,000182436,"31.31611, 121.11576","30.93646, 121.46803",2017-02-07,2017-02-07 01:01:28,2019-01-16 22:04:04,NaT,2017-02-08 23:59:00,0 days 01:01:28,NaT,CHN,TMS,LFL
1,CHN,NO-LIMIT,TSX0,000182584,"31.31611, 121.11576","30.93646, 121.46803",2017-02-07,2017-02-07 01:01:28,2019-01-16 22:04:04,NaT,2017-02-08 23:59:00,0 days 01:01:28,NaT,CHN,TMS,LFL
2,CHN,NO-LIMIT,TSX0,000183341,"31.31611, 121.11576","30.93646, 121.46803",2017-02-07,2017-02-07 01:01:28,2019-01-16 22:04:04,NaT,2017-02-08 23:59:00,0 days 01:01:28,NaT,CHN,TMS,LFL
3,CHN,NO-LIMIT,TSX0,000183345,"31.31611, 121.11576","30.93646, 121.46803",2017-02-07,2017-02-07 01:01:28,2019-01-16 22:04:04,NaT,2017-02-08 23:59:00,0 days 01:01:28,NaT,CHN,TMS,LFL
4,CHN,NO-LIMIT,TSX0,000183763,"31.31611, 121.11576","30.93646, 121.46803",2017-02-07,2017-02-07 01:01:28,2019-01-16 22:04:04,NaT,2017-02-08 23:59:00,0 days 01:01:28,NaT,CHN,TMS,LFL
5,CHN,NO-LIMIT,TSX0,000849539,"31.04988, 120.78709","31.38743, 121.47725",2018-01-16,2018-01-16 01:16:49,2019-01-15 12:40:00,NaT,NaT,0 days 01:16:49,NaT,CHN,TMS,LFL
6,CHN,NO-LIMIT,TSX0,000849540,"31.04988, 120.78709","31.38743, 121.47725",2018-01-16,2018-01-16 01:16:49,2019-01-15 12:40:00,NaT,NaT,0 days 01:16:49,NaT,CHN,TMS,LFL
7,CHN,NO-LIMIT,TSX0,000849541,"31.04988, 120.78709","31.38743, 121.47725",2018-01-16,2018-01-16 01:16:49,2019-01-15 12:40:00,NaT,NaT,0 days 01:16:49,NaT,CHN,TMS,LFL
8,CHN,NO-LIMIT,TSX0,000849542,"31.04988, 120.78709","31.38743, 121.47725",2018-01-16,2018-01-16 01:16:49,2019-01-15 12:40:00,NaT,NaT,0 days 01:16:49,NaT,CHN,TMS,LFL
9,CHN,NO-LIMIT,TSX0,000849545,"31.04988, 120.78709","31.38743, 121.47725",2018-01-16,2018-01-16 01:16:49,2019-01-15 12:40:00,NaT,NaT,0 days 01:16:49,NaT,CHN,TMS,LFL
10,CHN,NO-LIMIT,TSX0,000849546,"31.04988, 120.78709","31.38743, 121.47725",2018-01-16,2018-01-16 01:16:49,2019-01-15 12:40:00,NaT,NaT,0 days 01:16:49,NaT,CHN,TMS,LFL
11,CHN,NO-LIMIT,TSX0,000849547,"31.04988, 120.78709","31.38743, 121.47725",2018-01-16,2018-01-16 01:16:49,2019-01-15 12:40:00,NaT,NaT,0 days 01:16:49,NaT,CHN,TMS,LFL
12,CHN,NO-LIMIT,TSX0,000849548,"31.04988, 120.78709","31.38743, 121.47725",2018-01-16,2018-01-16 01:16:49,2019-01-15 12:40:00,NaT,NaT,0 days 01:16:49,NaT,CHN,TMS,LFL
13,CHN,NO-LIMIT,TSX0,000849549,"31.04988, 120.78709","31.38743, 121.47725",2018-01-16,2018-01-16 01:16:49,2019-01-15 12:40:00,NaT,NaT,0 days 01:16:49,NaT,CHN,TMS,LFL
14,CHN,NO-LIMIT,TSX0,000849550,"31.04988, 120.78709","31.38743, 121.47725",2018-01-16,2018-01-16 01:16:49,2019-01-15 12:40:00,NaT,NaT,0 days 01:16:49,NaT,CHN,TMS,LFL

In [2]:
#Current Strategy for Testing the Data
#data set = HKG, Date = 2019-01-02, Time = 11:40:55

df_hkg = df[df["Loc"] == "HKG"]
#df_hkg["Date"] = df_hkg["planStartTime"].dt.date.astype(str)
df_hkg["Year"] = df_hkg["planStartTime"].dt.year.astype(str)
df_hkg = df_hkg[df_hkg["Year"] == "2019"].drop({"Year"}, axis=1)
#df_hkg["Time"] = df_hkg["planStartTime"].dt.time.astype(str)
#df_hkg = df_hkg[df_hkg["Time"] == "11:40:55"].drop({"Time"}, axis=1).sort_values(by=["planStartTime"])
#df_hkg = df_hkg.drop_duplicates(subset=['destLoc'], keep="first", inplace=False)
df_hkg.index = np.arange(1, len(df_hkg) + 1)

#Assume only go to a dest once per journey
#1.Actual Start Time >= Planned Start Time
#2. Plan Duration > 0
#3. Actual Duration > 0
#4. Time-4 Not Null
#5. Check Time 1-3 Null? If null then drop
#6. Cal journey time by OSM, and set threshold for the actual Duration, intial 10 times

#df_hkg = df_hkg.drop_duplicates(subset=['Loc', 'Vehicle', 'origLoc', 'destLoc', 'planStartTime', 'planEndTime'], keep="first", inplace=False)
df_hkg.head(5)

/var/folders/rx/s42f27kn5j5ddqzlhz7qr2yw0000gn/T/ipykernel_2516/354592436.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hkg["Year"] = df_hkg["planStartTime"].dt.year.astype(str)

,Loc,Vehicle,warehouse,shipNo,origLoc,destLoc,planStartTime,planEndTime,actStartTime,actEndTime,MiscTime,planDurn,actDurn,countryCode,sysCode,companyCode
1,HKG,VAN-3_2,TSW0,025786907,"22.45055, 114.01209","22.45055, 114.01209",2019-01-02 06:00:00,2019-01-02 07:17:19,2019-01-02 06:00:00,2019-01-07 11:19:42,2019-01-02 21:00:00,0 days 01:17:19,5 days 05:19:42,HKG,TMS,LFL
2,HKG,VAN-3_2,TSW0,025786909,"22.45055, 114.01209","22.45055, 114.01209",2019-01-02 06:00:00,2019-01-02 07:17:19,2019-01-02 06:00:00,2019-01-07 11:19:42,2019-01-02 21:00:00,0 days 01:17:19,5 days 05:19:42,HKG,TMS,LFL
3,HKG,VAN-3_2,TSW0,025786911,"22.45055, 114.01209","22.45055, 114.01209",2019-01-02 06:00:00,2019-01-02 07:17:19,2019-01-02 06:00:00,2019-01-07 11:19:42,2019-01-02 21:00:00,0 days 01:17:19,5 days 05:19:42,HKG,TMS,LFL
4,HKG,VAN-3_2,TSW0,025786913,"22.45055, 114.01209","22.45055, 114.01209",2019-01-02 06:00:00,2019-01-02 07:17:19,2019-01-02 06:00:00,2019-01-07 11:19:42,2019-01-02 21:00:00,0 days 01:17:19,5 days 05:19:42,HKG,TMS,LFL
5,HKG,VAN-3_2,TSW0,025786915,"22.45055, 114.01209","22.45055, 114.01209",2019-01-02 06:00:00,2019-01-02 07:17:19,2019-01-02 06:00:00,2019-01-07 11:19:42,2019-01-02 21:00:00,0 days 01:17:19,5 days 05:19:42,HKG,TMS,LFL

In [3]:
#primary_list: [columns] agg_col: columns to be aggregated to the new df
def drop_duplicate(dataframe, agg_col:str, primary_lists:list):
    ascend_boolean = []
    for item in primary_lists:
        ascend_boolean.append(True)
    dataframe.sort_values(primary_lists, axis=0, ascending=ascend_boolean, inplace=True, na_position="first")

    col_name = list(dataframe.columns.values)
    col_loc = col_name.index(agg_col)

    agg_col_cloned = agg_col+"_index"
    
    dataframe['is_duplicated'] = dataframe.duplicated(subset=primary_lists)
    
    index = 0
    dataframe["is_duplicated_index"] = 0
    shipNoDict = {}
    shipNoDictKey = []
    checker = False

    for idx, row in dataframe.iterrows():
        shipNoDictKey.append(row[agg_col])
        if row["is_duplicated"] == False:
            dataframe.loc[idx, "is_duplicated_index"] += index
            shipNoDict.update({index: shipNoDictKey})
            index += 1
            shipNoDictKey=[]
        elif row["is_duplicated"] == True:
            dataframe.loc[idx, "is_duplicated_index"] += -1
        
    dataframe = dataframe[dataframe["is_duplicated_index"]!=-1]
    dataframe[agg_col_cloned] = dataframe['is_duplicated_index'].map(shipNoDict)
    col_name[col_loc] = agg_col_cloned
    dataframe = dataframe[col_name]
    col_name[col_loc] = agg_col
    dataframe.rename({agg_col_cloned: agg_col})
    dataframe.reset_index(inplace=True)
    print(dataframe.columns)
    #dataframe = dataframe.drop(['is_duplicated', 'is_duplicated_index', 'index'], axis=1)
    dataframe = dataframe.drop(['index'], axis=1)

    return dataframe

In [4]:

df_hkg = df[df["Loc"] == "HKG"]
df_hkg_cleansed = drop_duplicate(df_hkg, 'shipNo', ['Loc', 'Vehicle', 'origLoc', 'destLoc', 'planStartTime', 'planEndTime', 'actStartTime', 'actEndTime'])
df_hkg_cleansed.to_csv('df_hkg_cleansed.csv')
df_hkg_cleansed.head(20)

/var/folders/rx/s42f27kn5j5ddqzlhz7qr2yw0000gn/T/ipykernel_2516/3278462153.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe.sort_values(primary_lists, axis=0, ascending=ascend_boolean, inplace=True, na_position="first")
/var/folders/rx/s42f27kn5j5ddqzlhz7qr2yw0000gn/T/ipykernel_2516/3278462153.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['is_duplicated'] = dataframe.duplicated(subset=primary_lists)
/var/folders/rx/s42f27kn5j5ddqzlhz7qr2yw0000gn/T/ipykernel_2516/3278462153.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["is_duplicated_index"] = 0
/var/folders/rx/s42f27kn5j5ddqzlhz7qr2yw0000gn/T/ipykernel_2516/3278462153.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[agg_col_cloned] = dataframe['is_duplicated_index'].map(shipNoDict)

Index(['index', 'Loc', 'Vehicle', 'warehouse', 'shipNo_index', 'origLoc',
       'destLoc', 'planStartTime', 'planEndTime', 'actStartTime', 'actEndTime',
       'MiscTime', 'planDurn', 'actDurn', 'countryCode', 'sysCode',
       'companyCode'],
      dtype='object')

,Loc,Vehicle,warehouse,shipNo_index,origLoc,destLoc,planStartTime,planEndTime,actStartTime,actEndTime,MiscTime,planDurn,actDurn,countryCode,sysCode,companyCode
0,HKG,10T-17,OBX0,[002237149],"22.36991, 114.13556","22.27744, 114.16519",2019-12-02 08:00:00,2019-12-02 11:14:17,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 03:14:17,NaT,HKG,TMS,LFL
1,HKG,10T-17,OBX0,"[002237167, 002237301, 002237342, 002237352, 0...","22.36991, 114.13556","22.27821, 114.18209",2019-12-02 08:00:00,2019-12-02 11:06:04,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 03:06:04,NaT,HKG,TMS,LFL
2,HKG,10T-17,OBX0,"[002237209, 002237355, 002237423, 002237504, 0...","22.36991, 114.13556","22.27825, 114.18215",2019-12-02 08:00:00,2019-12-02 11:06:04,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 03:06:04,NaT,HKG,TMS,LFL
3,HKG,10T-17,OBW0,"[002237137, 002237138, 002237144, 002237176, 0...","22.36991, 114.13556","22.2783, 114.1801",2019-12-02 08:00:00,2019-12-02 09:14:53,2019-12-02 08:00:00,2019-12-01 23:31:50,2019-12-02 18:00:00,0 days 01:14:53,-1 days +15:31:50,HKG,TMS,LFL
4,HKG,10T-17,OBX0,"[029090934, 029090935, 002237100]","22.36991, 114.13556","22.27859, 114.18517",2019-12-02 08:00:00,2019-12-02 11:14:17,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 03:14:17,NaT,HKG,TMS,LFL
5,HKG,10T-17,OBX0,"[002237125, 002237127, 002237139, 002237145, 0...","22.36991, 114.13556","22.28042, 114.18443",2019-12-02 08:00:00,2019-12-02 11:14:17,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 03:14:17,NaT,HKG,TMS,LFL
6,HKG,10T-17,OBX0,"[002237115, 002237123, 002237227, 002237250, 0...","22.36991, 114.13556","22.28588, 114.15813",2019-12-02 08:00:00,2019-12-02 09:56:20,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 01:56:20,NaT,HKG,TMS,LFL
7,HKG,10T-17,OBW0,"[002237136, 002237141, 002237158, 002237208, 0...","22.36991, 114.13556","22.29525, 114.16511",2019-12-02 08:00:00,2019-12-02 09:14:53,2019-12-02 08:00:00,2019-12-01 23:31:50,2019-12-02 18:00:00,0 days 01:14:53,-1 days +15:31:50,HKG,TMS,LFL
8,HKG,10T-17,OBX0,"[029075068, 029090921, 029090922, 002237107]","22.36991, 114.13556","22.29525, 114.16511",2019-12-02 08:00:00,2019-12-02 09:56:20,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 01:56:20,NaT,HKG,TMS,LFL
9,HKG,10T-17,OBX0,"[002237361, 002237518, 002237681, 002237682, 0...","22.36991, 114.13556","22.29705, 114.16849",2019-12-02 08:00:00,2019-12-02 09:57:24,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 01:57:24,NaT,HKG,TMS,LFL
10,HKG,10T-17,OBX0,"[002237159, 002237179, 002237193, 002237244, 0...","22.36991, 114.13556","22.30067, 114.17219",2019-12-02 08:00:00,2019-12-02 09:56:20,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 01:56:20,NaT,HKG,TMS,LFL
11,HKG,10T-17,OBW0,"[002237362, 002237519, 002237520, 002237697, 0...","22.36991, 114.13556","22.30098, 114.17025",2019-12-02 08:00:00,2019-12-02 09:14:53,2019-12-02 08:00:00,2019-12-01 23:31:50,2019-12-02 18:00:00,0 days 01:14:53,-1 days +15:31:50,HKG,TMS,LFL
12,HKG,10T-17,OBX0,"[029090926, 002237110]","22.36991, 114.13556","22.30343, 114.16303",2019-12-02 08:00:00,2019-12-02 09:30:00,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 01:30:00,NaT,HKG,TMS,LFL
13,HKG,10T-17,OBX0,"[002237118, 002237128, 002237146, 002237151, 0...","22.36991, 114.13556","22.31631, 113.93555",2019-12-02 08:00:00,2019-12-02 09:31:47,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 01:31:47,NaT,HKG,TMS,LFL
14,HKG,10T-17,OBW0,"[002237165, 002237168, 002237220, 002237225, 0...","22.36991, 114.13556","22.323, 114.16979",2019-12-02 08:00:00,2019-12-02 09:14:53,2019-12-02 08:00:00,2019-12-01 23:31:50,2019-12-02 18:00:00,0 days 01:14:53,-1 days +15:31:50,HKG,TMS,LFL
15,HKG,10T-17,OBX0,"[029075075, 029075076, 029090930, 029090931, 0...","22.36991, 114.13556","22.32328, 114.17236",2019-12-02 08:00:00,2019-12-02 09:57:24,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 01:57:24,NaT,HKG,TMS,LFL
16,HKG,10T-17,OBX0,"[002237379, 002237380, 002237538, 002237699, 0...","22.36991, 114.13556","22.38164, 114.18926",2019-12-02 08:00:00,2019-12-02 08:12:13,2019-12-02 08:00:00,NaT,2019-12-02 20:00:00,0 days 00:12:13,NaT,HKG,TMS,LFL
17,HKG,10T-17,OBW0,"[002237392, 002237470, 002237624, 029075082]","22.36991, 114.13556","22.38164, 114.18926",2019-12-02 08:00:00,2019-12-02 09:14:53,2019-12-02 08:00:00,2019-12-01 23:31:50,2019-12-02 18:00:00,0 days 01:14:53,-1 days +15:31:50,HKG,TMS,LFL
18,HKG,10T-17,OBX0,"[029075083, 029090937, 029090938, 002641999]","22.39021, 114.20701","22.26301, 114.24945",2020-04-08 08:00:00,2020-04-08 12:27:36,2020-04-08 08:00:00,NaT,2020-04-08 20:00:00,0 days 04:27:36,NaT,HKG,TMS,LFL
19,HKG,10T-17,OBX0,[002642497],"22.39021, 114.20701","22.26399, 114.23708",2020-04-08 08:00:00,2020-04-08 12:27:36,2020-04-08 08:00:00,NaT,2020-04-08 20:00:00,0 days 04:27:36,NaT,HKG,TMS,LFL

In [5]:
df_hkg_cleansed_cleansed = drop_duplicate(df_hkg_cleansed, 'destLoc', ['Loc', 'Vehicle', 'origLoc', 'planStartTime', 'planEndTime', 'actStartTime', 'actEndTime'])

Index(['index', 'Loc', 'Vehicle', 'warehouse', 'shipNo_index', 'origLoc',
       'destLoc_index', 'planStartTime', 'planEndTime', 'actStartTime',
       'actEndTime', 'MiscTime', 'planDurn', 'actDurn', 'countryCode',
       'sysCode', 'companyCode'],
      dtype='object')

/var/folders/rx/s42f27kn5j5ddqzlhz7qr2yw0000gn/T/ipykernel_2516/3278462153.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[agg_col_cloned] = dataframe['is_duplicated_index'].map(shipNoDict)

In [6]:
df_hkg_cleansed_cleansed = df_hkg_cleansed_cleansed.sort_values(by=['planStartTime'])
df_hkg_cleansed_cleansed.head(30)

,Loc,Vehicle,warehouse,shipNo_index,origLoc,destLoc_index,planStartTime,planEndTime,actStartTime,actEndTime,MiscTime,planDurn,actDurn,countryCode,sysCode,companyCode
8048,HKG,VAN-3_2,TSW0,"[025798803, 025795682]","22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-02 06:00:00,2019-01-02 11:31:16,2019-01-02 06:00:00,NaT,2019-01-02 21:00:00,0 days 05:31:16,NaT,HKG,TMS,LFL
7857,HKG,VAN-1_6,TSW0,[025790170],"22.45055, 114.01209","[22.27765, 114.16522, 22.27825, 114.18215, 22....",2019-01-02 06:00:00,2019-01-02 07:51:09,2019-01-02 06:00:00,2019-01-07 01:43:49,2019-01-02 21:00:00,0 days 01:51:09,4 days 19:43:49,HKG,TMS,LFL
8047,HKG,VAN-3_2,TSW0,[025785776],"22.45055, 114.01209","[22.35673, 114.12773, 22.37382, 114.11763, 22....",2019-01-02 06:00:00,2019-01-02 09:53:26,2019-01-02 06:00:00,NaT,2019-01-02 21:00:00,0 days 03:53:26,NaT,HKG,TMS,LFL
8046,HKG,VAN-3_2,TSW0,[025794025],"22.45055, 114.01209","[22.45055, 114.01209, 22.28942, 113.9412]",2019-01-02 06:00:00,2019-01-02 09:19:51,2019-01-02 06:00:00,NaT,2019-01-02 21:00:00,0 days 03:19:51,NaT,HKG,TMS,LFL
8045,HKG,VAN-3_2,TSW0,"[032259328, 025787692]","22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-02 06:00:00,2019-01-02 07:17:19,2019-01-02 06:00:00,2019-01-07 11:19:42,2019-01-02 21:00:00,0 days 01:17:19,5 days 05:19:42,HKG,TMS,LFL
5925,HKG,LF-DUMMY,TSX0,"[001836784, 001836803, 001838815, 001873957]","22.44591, 114.03469","[22.27821, 114.18209, 22.2785, 114.1835, 22.28...",2019-01-02 11:40:54,2019-01-02 11:44:54,2019-01-02 11:40:54,NaT,2019-01-02 21:00:00,0 days 00:04:00,NaT,HKG,TMS,LFL
8049,HKG,VAN-3_2,TSX0,[001873962],"22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-02 11:40:55,2019-01-02 15:14:23,2019-01-02 11:40:55,NaT,2019-01-02 21:00:00,0 days 03:33:28,NaT,HKG,TMS,LFL
8054,HKG,VAN-3_2,TSW0,"[025795683, 025795691, 025795704, 025795771, 0...","22.45055, 114.01209","[22.31245, 114.22519, 22.32708, 114.18934, 22....",2019-01-03 06:00:00,2019-01-03 09:46:49,2019-01-03 06:00:00,NaT,2019-01-03 21:00:00,0 days 03:46:49,NaT,HKG,TMS,LFL
8055,HKG,VAN-3_2,TSW0,"[025798271, 025798312, 025798738, 025799152, 0...","22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-03 06:00:00,2019-01-03 11:31:16,2019-01-03 06:00:00,2019-01-14 05:57:11,2019-01-03 21:00:00,0 days 05:31:16,10 days 23:57:11,HKG,TMS,LFL
7858,HKG,VAN-1_6,TSW0,[025797103],"22.45055, 114.01209","[22.44591, 114.03469, 22.28942, 113.9412]",2019-01-03 06:00:00,2019-01-03 07:51:09,2019-01-03 06:00:00,2019-01-10 01:45:37,2019-01-03 21:00:00,0 days 01:51:09,6 days 19:45:37,HKG,TMS,LFL
8050,HKG,VAN-3_2,TSW0,"[001873955, 001873956, 001873965, 025797072]","22.45055, 114.01209","[22.3077, 114.25998, 22.31245, 114.22519, 22.3...",2019-01-03 06:00:00,2019-01-03 07:30:34,2019-01-03 06:00:00,2019-01-04 12:42:16,2019-01-03 21:00:00,0 days 01:30:34,1 days 06:42:16,HKG,TMS,LFL
8051,HKG,VAN-3_2,TSW0,[025796531],"22.45055, 114.01209","[22.44591, 114.03469, 22.3136, 114.17052]",2019-01-03 06:00:00,2019-01-03 08:53:31,2019-01-03 06:00:00,NaT,2019-01-03 21:00:00,0 days 02:53:31,NaT,HKG,TMS,LFL
8052,HKG,VAN-3_2,TSX0,[001874876],"22.45055, 114.01209","[22.32708, 114.18934, 22.33756, 114.14845, 22....",2019-01-03 06:00:00,2019-01-03 09:23:31,2019-01-03 06:00:00,NaT,2019-01-03 21:00:00,0 days 03:23:31,NaT,HKG,TMS,LFL
8053,HKG,VAN-3_2,TSW0,[025807283],"22.45055, 114.01209","[22.33756, 114.14845, 22.35673, 114.12773, 22....",2019-01-03 06:00:00,2019-01-03 09:42:58,2019-01-03 06:00:00,NaT,2019-01-03 21:00:00,0 days 03:42:58,NaT,HKG,TMS,LFL
19,HKG,16T-20_4,OBWL,"[029907880, 029928882, 029938618, 029992807, 0...","22.36991, 114.13556","[22.44576, 114.03522]",2019-01-03 07:00:00,2019-01-03 12:18:53,2019-01-03 07:00:00,NaT,2019-01-03 18:00:00,0 days 05:18:53,NaT,HKG,TMS,LFL
17,HKG,16T-20_4,OBW0,[025786756],"22.36991, 114.13556","[22.27972, 114.18458]",2019-01-03 07:00:00,2019-01-03 08:05:11,2019-01-03 07:00:00,NaT,2019-01-03 18:00:00,0 days 01:05:11,NaT,HKG,TMS,LFL
18,HKG,16T-20_4,OBWL,"[031162607, 031162608, 031165027, 031165028, 0...","22.36991, 114.13556","[22.28516, 114.15884]",2019-01-03 07:00:00,2019-01-03 09:28:18,2019-01-03 07:00:00,NaT,2019-01-03 18:00:00,0 days 02:28:18,NaT,HKG,TMS,LFL
16,HKG,16T-20_4,OBWL,"[031165010, 031165011, 031165012, 031165013, 0...","22.36991, 114.13556","[22.27972, 114.18458]",2019-01-03 07:00:00,2019-01-03 07:22:13,2019-01-03 07:00:00,NaT,2019-01-03 18:00:00,0 days 00:22:13,NaT,HKG,TMS,LFL
8059,HKG,VAN-3_2,TSW0,[025806280],"22.45055, 114.01209","[22.27936, 114.22872, 22.31245, 114.22519, 22....",2019-01-04 06:00:00,2019-01-04 10:28:07,2019-01-04 06:00:00,NaT,2019-01-04 21:00:00,0 days 04:28:07,NaT,HKG,TMS,LFL
8060,HKG,VAN-3_2,TSW0,"[025807092, 025807216, 025807221, 025807583, 0...","22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-04 06:00:00,2019-01-04 10:56:35,2019-01-04 06:00:00,2019-01-12 02:04:05,2019-01-04 21:00:00,0 days 04:56:35,7 days 20:04:05,HKG,TMS,LFL
8058,HKG,VAN-3_2,TSW0,"[025796776, 025796778, 025798639, 025822881]","22.45055, 114.01209","[22.39502, 113.97302, 22.44591, 114.03469, 22....",2019-01-04 06:00:00,2019-01-04 09:55:08,2019-01-04 06:00:00,NaT,2019-01-04 21:00:00,0 days 03:55:08,NaT,HKG,TMS,LFL
8057,HKG,VAN-3_2,TSW0,[025807056],"22.45055, 114.01209","[22.35673, 114.12773, 22.37382, 114.11763, 22....",2019-01-04 06:00:00,2019-01-04 08:43:59,2019-01-04 06:00:00,NaT,2019-01-04 21:00:00,0 days 02:43:59,NaT,HKG,TMS,LFL
8056,HKG,VAN-3_2,TSX0,"[025796766, 025796768, 025796772, 025798544, 0...","22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-04 06:00:00,2019-01-04 08:15:50,2019-01-04 06:00:00,NaT,2019-01-04 21:00:00,0 days 02:15:50,NaT,HKG,TMS,LFL
7859,HKG,VAN-1_6,TSW0,"[025805834, 025806976, 025806222]","22.45055, 114.01209","[22.44591, 114.03469, 22.28942, 113.9412]",2019-01-04 06:00:00,2019-01-04 07:51:09,2019-01-04 06:00:00,2019-01-12 06:26:43,2019-01-04 21:00:00,0 days 01:51:09,8 days 00:26:43,HKG,TMS,LFL
20,HKG,16T-20_4,OBWL,[001766993],"22.36991, 114.13556","[22.27972, 114.18458]",2019-01-04 07:00:00,2019-01-04 07:22:13,2019-01-04 07:00:00,NaT,2019-01-04 18:00:00,0 days 00:22:13,NaT,HKG,TMS,LFL
21,HKG,16T-20_4,OBWL,[001766995],"22.36991, 114.13556","[22.28516, 114.15884]",2019-01-04 07:00:00,2019-01-04 09:17:07,2019-01-04 07:00:00,NaT,2019-01-04 18:00:00,0 days 02:17:07,NaT,HKG,TMS,LFL
22,HKG,16T-20_4,OBWL,[001766994],"22.36991, 114.13556","[22.44576, 114.03522]",2019-01-04 07:00:00,2019-01-04 12:10:14,2019-01-04 07:00:00,NaT,2019-01-04 18:00:00,0 days 05:10:14,NaT,HKG,TMS,LFL
8063,HKG,VAN-3_2,TSW0,"[025811220, 025811236, 025821623]","22.45055, 114.01209","[22.28035, 114.18507, 22.28208, 114.15772, 22....",2019-01-05 06:00:00,2019-01-05 11:07:00,2019-01-05 06:00:00,NaT,2019-01-05 21:00:00,0 days 05:07:00,NaT,HKG,TMS,LFL
8062,HKG,VAN-3_2,TSW0,"[025807580, 025807928, 025810638, 025810640, 0...","22.45055, 114.01209","[22.38215, 114.18678, 22.39502, 113.97302, 22....",2019-01-05 06:00:00,2019-01-05 09:45:56,2019-01-05 06:00:00,2019-01-11 05:18:33,2019-01-05 21:00:00,0 days 03:45:56,5 days 23:18:33,HKG,TMS,LFL
8061,HKG,VAN-3_2,TSX0,"[025807975, 025811222, 025811537, 001880570]","22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-05 06:00:00,2019-01-05 08:34:58,2019-01-05 06:00:00,NaT,2019-01-05 21:00:00,0 days 02:34:58,NaT,HKG,TMS,LFL

In [7]:
df_hkg_2019 = df_hkg_cleansed_cleansed
df_hkg_2019["Year"] = df_hkg_2019["planStartTime"].dt.year.astype(str)
df_hkg_2019 = df_hkg_2019[df_hkg_2019["Year"] == "2019"].drop({"Year"}, axis=1)
df_hkg_2019.head(20)

,Loc,Vehicle,warehouse,shipNo_index,origLoc,destLoc_index,planStartTime,planEndTime,actStartTime,actEndTime,MiscTime,planDurn,actDurn,countryCode,sysCode,companyCode
8048,HKG,VAN-3_2,TSW0,"[025798803, 025795682]","22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-02 06:00:00,2019-01-02 11:31:16,2019-01-02 06:00:00,NaT,2019-01-02 21:00:00,0 days 05:31:16,NaT,HKG,TMS,LFL
7857,HKG,VAN-1_6,TSW0,[025790170],"22.45055, 114.01209","[22.27765, 114.16522, 22.27825, 114.18215, 22....",2019-01-02 06:00:00,2019-01-02 07:51:09,2019-01-02 06:00:00,2019-01-07 01:43:49,2019-01-02 21:00:00,0 days 01:51:09,4 days 19:43:49,HKG,TMS,LFL
8047,HKG,VAN-3_2,TSW0,[025785776],"22.45055, 114.01209","[22.35673, 114.12773, 22.37382, 114.11763, 22....",2019-01-02 06:00:00,2019-01-02 09:53:26,2019-01-02 06:00:00,NaT,2019-01-02 21:00:00,0 days 03:53:26,NaT,HKG,TMS,LFL
8046,HKG,VAN-3_2,TSW0,[025794025],"22.45055, 114.01209","[22.45055, 114.01209, 22.28942, 113.9412]",2019-01-02 06:00:00,2019-01-02 09:19:51,2019-01-02 06:00:00,NaT,2019-01-02 21:00:00,0 days 03:19:51,NaT,HKG,TMS,LFL
8045,HKG,VAN-3_2,TSW0,"[032259328, 025787692]","22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-02 06:00:00,2019-01-02 07:17:19,2019-01-02 06:00:00,2019-01-07 11:19:42,2019-01-02 21:00:00,0 days 01:17:19,5 days 05:19:42,HKG,TMS,LFL
5925,HKG,LF-DUMMY,TSX0,"[001836784, 001836803, 001838815, 001873957]","22.44591, 114.03469","[22.27821, 114.18209, 22.2785, 114.1835, 22.28...",2019-01-02 11:40:54,2019-01-02 11:44:54,2019-01-02 11:40:54,NaT,2019-01-02 21:00:00,0 days 00:04:00,NaT,HKG,TMS,LFL
8049,HKG,VAN-3_2,TSX0,[001873962],"22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-02 11:40:55,2019-01-02 15:14:23,2019-01-02 11:40:55,NaT,2019-01-02 21:00:00,0 days 03:33:28,NaT,HKG,TMS,LFL
8054,HKG,VAN-3_2,TSW0,"[025795683, 025795691, 025795704, 025795771, 0...","22.45055, 114.01209","[22.31245, 114.22519, 22.32708, 114.18934, 22....",2019-01-03 06:00:00,2019-01-03 09:46:49,2019-01-03 06:00:00,NaT,2019-01-03 21:00:00,0 days 03:46:49,NaT,HKG,TMS,LFL
8055,HKG,VAN-3_2,TSW0,"[025798271, 025798312, 025798738, 025799152, 0...","22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-03 06:00:00,2019-01-03 11:31:16,2019-01-03 06:00:00,2019-01-14 05:57:11,2019-01-03 21:00:00,0 days 05:31:16,10 days 23:57:11,HKG,TMS,LFL
7858,HKG,VAN-1_6,TSW0,[025797103],"22.45055, 114.01209","[22.44591, 114.03469, 22.28942, 113.9412]",2019-01-03 06:00:00,2019-01-03 07:51:09,2019-01-03 06:00:00,2019-01-10 01:45:37,2019-01-03 21:00:00,0 days 01:51:09,6 days 19:45:37,HKG,TMS,LFL
8050,HKG,VAN-3_2,TSW0,"[001873955, 001873956, 001873965, 025797072]","22.45055, 114.01209","[22.3077, 114.25998, 22.31245, 114.22519, 22.3...",2019-01-03 06:00:00,2019-01-03 07:30:34,2019-01-03 06:00:00,2019-01-04 12:42:16,2019-01-03 21:00:00,0 days 01:30:34,1 days 06:42:16,HKG,TMS,LFL
8051,HKG,VAN-3_2,TSW0,[025796531],"22.45055, 114.01209","[22.44591, 114.03469, 22.3136, 114.17052]",2019-01-03 06:00:00,2019-01-03 08:53:31,2019-01-03 06:00:00,NaT,2019-01-03 21:00:00,0 days 02:53:31,NaT,HKG,TMS,LFL
8052,HKG,VAN-3_2,TSX0,[001874876],"22.45055, 114.01209","[22.32708, 114.18934, 22.33756, 114.14845, 22....",2019-01-03 06:00:00,2019-01-03 09:23:31,2019-01-03 06:00:00,NaT,2019-01-03 21:00:00,0 days 03:23:31,NaT,HKG,TMS,LFL
8053,HKG,VAN-3_2,TSW0,[025807283],"22.45055, 114.01209","[22.33756, 114.14845, 22.35673, 114.12773, 22....",2019-01-03 06:00:00,2019-01-03 09:42:58,2019-01-03 06:00:00,NaT,2019-01-03 21:00:00,0 days 03:42:58,NaT,HKG,TMS,LFL
19,HKG,16T-20_4,OBWL,"[029907880, 029928882, 029938618, 029992807, 0...","22.36991, 114.13556","[22.44576, 114.03522]",2019-01-03 07:00:00,2019-01-03 12:18:53,2019-01-03 07:00:00,NaT,2019-01-03 18:00:00,0 days 05:18:53,NaT,HKG,TMS,LFL
17,HKG,16T-20_4,OBW0,[025786756],"22.36991, 114.13556","[22.27972, 114.18458]",2019-01-03 07:00:00,2019-01-03 08:05:11,2019-01-03 07:00:00,NaT,2019-01-03 18:00:00,0 days 01:05:11,NaT,HKG,TMS,LFL
18,HKG,16T-20_4,OBWL,"[031162607, 031162608, 031165027, 031165028, 0...","22.36991, 114.13556","[22.28516, 114.15884]",2019-01-03 07:00:00,2019-01-03 09:28:18,2019-01-03 07:00:00,NaT,2019-01-03 18:00:00,0 days 02:28:18,NaT,HKG,TMS,LFL
16,HKG,16T-20_4,OBWL,"[031165010, 031165011, 031165012, 031165013, 0...","22.36991, 114.13556","[22.27972, 114.18458]",2019-01-03 07:00:00,2019-01-03 07:22:13,2019-01-03 07:00:00,NaT,2019-01-03 18:00:00,0 days 00:22:13,NaT,HKG,TMS,LFL
8059,HKG,VAN-3_2,TSW0,[025806280],"22.45055, 114.01209","[22.27936, 114.22872, 22.31245, 114.22519, 22....",2019-01-04 06:00:00,2019-01-04 10:28:07,2019-01-04 06:00:00,NaT,2019-01-04 21:00:00,0 days 04:28:07,NaT,HKG,TMS,LFL
8060,HKG,VAN-3_2,TSW0,"[025807092, 025807216, 025807221, 025807583, 0...","22.45055, 114.01209","[22.27936, 114.22872, 22.28035, 114.18507, 22....",2019-01-04 06:00:00,2019-01-04 10:56:35,2019-01-04 06:00:00,2019-01-12 02:04:05,2019-01-04 21:00:00,0 days 04:56:35,7 days 20:04:05,HKG,TMS,LFL

In [14]:
df_hkg_2019['Loc_node'] = df_hkg_2019['destLoc_index'].append(df_hkg_2019['origLoc'])
df_hkg_2019 = df_hkg_2019.drop({"destLoc_index"}, axis=1)
df_hkg_2019 = df_hkg_2019.drop({"origLoc"}, axis=1)
df_hkg_2019.head(10)

/var/folders/rx/s42f27kn5j5ddqzlhz7qr2yw0000gn/T/ipykernel_2516/4224485676.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_hkg_2019['Loc_node'] = df_hkg_2019['destLoc_index'].append(df_hkg_2019['origLoc'])
/var/folders/rx/s42f27kn5j5ddqzlhz7qr2yw0000gn/T/ipykernel_2516/4224485676.py:1: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  df_hkg_2019['Loc_node'] = df_hkg_2019['destLoc_index'].append(df_hkg_2019['origLoc'])

ValueError: cannot reindex on an axis with duplicate labels

In [19]:
df_hkg_201901.to_csv('df_hkg_201901.csv')

In [20]:
import osmnx as ox

hwy_speeds = {"residential": 10, "secondary": 33, "tertiary": 60}

def loadGraph(place="HK", optimizer="travel_time", mode = "drive", hwy_speeds=hwy_speeds):
    ox.config(log_console = True, use_cache = True)
    #mode = 'drive' # 'drive', 'bike', 'walk'
    graph = ox.graph_from_place(place, network_type = mode)
    graph = ox.add_edge_speeds(graph, hwy_speeds)
    graph = ox.add_edge_travel_times(graph)
    return graph

G = loadGraph("HK", "travel_time", "drive", hwy_speeds)
node0 = G.nodes(data=True)[1012751972]
node0['x'] #lon
node0['y'] #lat

/Users/ytsang/opt/anaconda3/lib/python3.9/site-packages/osmnx/utils.py:192: UserWarning: The `utils.config` function is deprecated and will be removed in a future release. Instead, use the `settings` module directly to configure a global setting's value. For example, `ox.settings.log_console=True`.
  warnings.warn(
Exception ignored in: <function BaseGeometry.__del__ at 0x7f96c61e8d30>
Traceback (most recent call last):
  File "/Users/ytsang/opt/anaconda3/lib/python3.9/site-packages/shapely/geometry/base.py", line 208, in __del__
    def __del__(self):
KeyboardInterrupt:

22.2781733

In [22]:
print(node0['y'], node0['x'])

22.2781733 114.1801764

In [23]:
node0 = G.nodes(data=True)[1703006759]
print(node0['y'], node0['x'])

22.3695665 114.1355884